---
taps:
  - caskroom/fonts 
brews:
  - automake
  - coreutils
  - cmake
  - exiftool
  - findutils
  - fzf
  - gawk
  - geoip
  - gdbm
  - git
  - go
  - gpg
  - graphviz
  - httpie
  - iperf
  - keepassc
  - libevent
  - libressl
  - libtool
  - mplayer
  - netcat
  - nmap
  - node
  - proxychains-ng
  - ssh-copy-id
  - screenresolution
  - openssl
  - python
  - python3
  - pv
  - swig
  - tmux
  - wget
  - xz
common_casks:
  - 1password
  - 1password-cli
  - adium
  - alfred
  - amazon-drive
  - docker
  - dropbox
  - emacs
  - emacsclient
  - firefox
  - google-chrome
  - hex-fiend
  - iterm2
  - little-snitch
  - spotify
  - slack
font_casks:
  - font-source-code-pro
  - font-source-code-pro-for-powerline
extra_casks:
  - adobe-photoshop-lightroom
root_casks:
  - crashplan
  - viscosity
  - wireshark
  - zoomus
