---
# tasks file for roles/golang
- name: Install golang
  homebrew:
    name: golang
    state: present

- name: Create go directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0775
  loop:
    - "{{ home_dir }}/go"
    - "{{ home_dir }}/go/bin"

- name: Set Go env vars for this run
  set_fact:
    gopath: "{{ home_dir }}/go"
    gobin: "{{ home_dir }}/go/bin"

- name: Set Go env vars
  blockinfile:
    path: "/etc/profile"
    block: |
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      export PATH=$PATH:$GOBIN
  become: true

- name: Install go packages
  command: "go get {{ item }}"
  environment:
    GOPATH: "{{ gopath }}"
  loop: "{{ go_packages }}"
