---
language: generic
os: osx
osx_image: xcode12u
services:
  - docker
install:
  - pip install molecule docker
script:
  - molecule --version
  - ansible --version
  - cd roles/wallpaper && molecule test
