---
language: generic
os: osx
osx_image: xcode12u
services:
  - docker
install:
  - pip install molecule
script:
  - molecule --version
  - ansible --version
  - cd roles/wallpaper && molecule lint && cd -
  - make bootstrap
  - make install

