---
language: python
os: osx
osx_image: xcode12u
python:
  - "3.7"
services:
  - docker
install:
  - pip install molecule docker
script:
  - molecule --version
  - ansible --version
  - molecule test
