---
#### Install packages using Homebrew
# brews list in vars/main
# casks list in vars/main
# extra casks for stuff I don't want on work machines
# add/remove as necessary
####

- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Install default packages from homebrew
  homebrew:
    name="{{ item }}"
    state=present
  with_items:
    - "{{ brews }}"

- name: Install packages from homebrew cask
  homebrew_cask:
    name="{{ item }}"
    state=present
  with_items:
    - "{{ common_casks }}"

- name: Install extra casks (useful for home laptop)
  homebrew_cask:
    name="{{ item }}"
    state=present
  when: "'osx-personal' in group_names"
  with_items:
    - "{{ extra_casks }}"
