---
#### Install packages using Homebrew
# brews list in vars/main
# casks list in vars/main
# extra casks for stuff I don't want on work machines
# add/remove as necessary
#
# linking the prereqs is a little dirty
####

- name: Fix perms on /usr/local
  file:
    path: "/usr/local/{{ item }}"
    owner: "{{ usernm }}"
    group: admin
    mode: 0775
    recurse: yes
    state: directory
  become: true
  become_user: root
  with_items:
    - bin
    - Caskroom
    - Cellar
    - etc
    - Homebrew
    - include
    - lib
    - opt
    - share
    - var

- name: Tap homebrew taps
  become: true
  become_user: "{{ usernm }}"
  homebrew_tap:
    name: "{{ item }}"
  with_items:
    "{{ taps }}"

- name: Update homebrew
  become: true
  become_user: "{{ usernm }}"
  homebrew:
    update_homebrew: yes

- name: Install default packages from homebrew
  become: true
  become_user: "{{ usernm }}"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ brews }}"

- name: Install packages from homebrew cask
  become: true
  become_user: "{{ usernm }}"
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: 'appdir={{ home_dir }}/Applications'
  with_items:
    "{{ common_casks }}"

- name: Install casks which need to be installed as root (via sudo)
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ root_casks }}"

- name: Install extra casks from homebrew
  become: true
  become_user: "{{ usernm }}"
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: 'appdir={{ home_dir }}/Applications'
  when: extra_casks
  with_items:
    "{{ extra_casks }}"

- name: Install fonts from homebrew cask
  become: true
  become_user: "{{ usernm }}"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ font_casks }}"
  register: font_install

- name: Clear font caches on new font
  become: true
  become_user: root
  command: atsutil databases -remove
  when: font_install.changed
