---
- name: Install homebrew (lil hacky to get unattended install)
  command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
    args:
      creates='/usr/local/bin/brew'
  register: brew_installed

- name: Update homebrew
  homebrew: update_homebrew=yes
  when: brew_installed.stat.exist == True

- name: Install default packages from homebrew
  homebrew:
    name="{{ item }}"
    state=present
  when: brew_installed.stat.exist == True
  with_items:
    "{{ brews }}"

- name: Install packages from homebrew cask
  homebrew_cask:
    name="{{ item }}"
    state=present
  with_items:
    "{{ common_casks }}"

- name: Install extra casks (useful for home laptop)
  homebrew_cask:
    name="{{ item }}"
    state=present
  when: 'osx-personal' in group_names
  with_items:
    "{{ extra_casks }}"
