---
#### Some base setup including ssh keys
# projects dir is set in vars/main
#
# ssh keys are the key pairs you want made
# by default it only creates id_rsa
# add an array in vars/main to overwrite
####

- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{ ssh_dir }}', mode: 0700 }

- name: Need known_hosts
  file:
    path: "{{ ssh_dir }}/known_hosts"
    state: file
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0644

- name: Create ssh key(s)
  command: ssh-keygen -t rsa -N "" -f {{ item }}
  with_items:
    - "{{ ssh_key_name }}"
  when: ssh_dir.stat.exists == True
