---
#### Some base setup including ssh keys
# projects dir is set in vars/main
# hostname is set in vars/main
#
# ssh_dir is set in defaults
# ssh_key_name is in defaults
# 
# usernm/groupnm set in group_vars/all (YOU MUST SET THESE)
####

- name: Set computer name
  become: true
  become_user: root
  command: "scutil --set {{ item }} {{ hostname }}"
  with_items:
    - ComputerName
    - HostName
    - LocalHostName

#- name: Defaults host name
#  osx_defaults:
#    domain: com.apple.smb.server
#    key: NetBIOSName
#    type: string
#    value: "{{ hostname }}"

- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{ projects_dir }}', mode: '0755' }
    - { path: '{{ ssh_dir }}', mode: '0700' }
    - { path: '{{ ansible_secrets }}', mode: '0700' }

- name: Check if key exists
  stat:
    path: "{{ ssh_key_name }}"
  register: ssh_key

- name: Create ssh key(s)
  command: ssh-keygen -t rsa -N '' -q -f "{{ ssh_key_name }}"
  when: (ssh_key.stat.exists == false)

- name: Set search domains
  command: networksetup -setsearchdomains "{{ search_domain_iface }}" es.net testbed100.es.net
  become: true
  become_user: root
  when: "'osx-work' in group_names"
