---
- name: Create directories
  file:
    path="{{ item.path }}"
    state=directory
    owner="{{ usernm }}"
    group="{{ usernm }}"
    mode="{{ item.mode }}"
  with_items:
    - { path: '{{ projects_dir }}', mode: '0775' }
    - { path: '{{ ansible_secrets }}', mode: '0775' }
    - { path: '{{ home_dir }}/.ssh', mode: '0700' }

- name: Create ssh key(s)
  command: ssh-keygen -t rsa -N "" -f {{ item }}
  with_items:
    "{{ ssh_keys }}"
  when: ssh_dir.stat.exists == True
