---
#### Some base setup including ssh keys
#
# ssh_key_name is in defaults
#
####

- name: Set computer name
  command: "scutil --set {{ item }} {{ hostname }}"
  with_items:
    - ComputerName
    - HostName
    - LocalHostName
  become: true
  become_user: root

- name: Defaults host name
  osx_defaults:
    domain: com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ hostname }}"
  become: true
  become_user: root

- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{ projects_dir }}', mode: '0755' }
    - { path: '{{ ssh_dir }}', mode: '0700' }
    - { path: '{{ ansible_secrets }}', mode: '0700' }

- name: Check if key exists
  stat:
    path: "{{ ssh_key_name }}"
  register: ssh_key

- name: Create ssh key(s)
  command: ssh-keygen -t rsa -N '' -q -f "{{ ssh_key_name }}"
  when: (ssh_key.stat.exists == false)

- name: Set search domains
  command: networksetup -setsearchdomains "{{ search_domain_iface }}" "{{ search_domains }}"
  become: true
  become_user: root
