---
#### Some base setup including ssh keys
# projects dir is set in vars/main
# hostname is set in vars/main
#
# ssh_dir is set in defaults
# ssh_key_name is in defaults
#
# usernm/groupnm set in group_vars/all (YOU MUST SET THESE)
####

# We want to add our user (if they don't exist already -- and have Ansible create an ssh key)

- name: Add normal user
  user:
    name: "{{ usernm }}"
    comment: "{{ full_name }}"
    group: "{{ groupnm }}"
    shell: "{{ shell }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519

- name: Create user home directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{ projects_dir }}', mode: '0755' }
    - { path: '{{ ansible_secrets }}', mode: '0700' }

- name: Configure git author
  become: true
  become_user: "{{ usernm }}"
  command: "{{ item }}"
  with_items:
  - git config --global user.email "{{ email }}"
  - git config --global user.name "{{ full_name }}"

# Set our hostname

- name: Set computer name
  command: "scutil --set {{ item }} {{ hostname }}"
  with_items:
    - ComputerName
    - HostName
    - LocalHostName

- name: Set search domains
  command: networksetup -setsearchdomains "{{ search_domain_iface }}" "{{ search_domains }}"
