---
#### Grab your dotfiles
# Set dotfiles_repo in vars/main
# dotfiles_dir is set in defaults, LEAVE ALONE
####

- name: Install powerline
  become: true
  become_user: "{{ usernm }}"
  pip:
    name: powerline-status
    extra_args: --user
- name: Get powerline path
  become: true
  become_user: "{{ usernm }}"
  shell: find "{{ home_dir }}" -name powerline.zsh
  register: powerline_path
- name: Install .zshrc template
  become: true
  become_user: root
  template:
    src: zshrc-template.j2
    dest: "{{ home_dir }}/.zshrc"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    backup: true
- name: Install .Xresources template (on Linux)
  become: true
  become_user: root
  template:
    src: xresources-template.j2
    dest: "{{ home_dir }}/.Xresources"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    backup: true
  when: ansible_os_family != "Darwin"
- name: Install .gitignore template
  become: true
  become_user: root
  template:
    src: gitignore-template.j2
    dest: "{{ home_dir }}/.gitignore"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    backup: trueA
- name: Create launchd directory
  become: true
  become_user: "{{ usernm }}"
  file:
    path: "{{ home_dir }}/Library/LaunchAgents"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0750
- name: Install .login_hook template
  become: true
  become_user: root
  template:
    src: loginhook-template.j2
    dest: "{{ home_dir }}/.remap_caps_lock_control"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0750
    backup: true
- name: Install .login_hook plist
  become: true
  become_user: root
  template:
    src: loginhook-plist-template.j2
    dest: "{{ home_dir }}/Library/LaunchAgents/CapsLockCtl.plist"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0640
    backup: true
- name: Create Wireshark directory
  become: true
  become_user: "{{ usernm }}"
  file:
    path: "{{ home_dir }}/.config/wireshark"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0750
- name: Create PCAP directory
  become: true
  become_user: "{{ usernm }}"
  file:
    path: "{{ home_dir }}/pcaps"
    state: directory
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0750
- name: Install Wireshark config
  become: true
  become_user: root
  template:
    src: wireshark-template.j2
    dest: "{{ home_dir }}/.config/wireshark/preferences"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    backup: true
- name: Create Firefox profile
  become: true
  become_user: "{{ usernm }}"
  command: '/Applications/Firefox.app/Contents/MacOS/firefox-bin -CreateProfile "HardenedDefault {{ home_dir }}/Library/Application Support/Firefox/Profiles/hardened.default"'
- name: Install Firefox preferences
  become: true
  become_user: root
  template:
    src: user_js_template.j2
    dest: "{{ home_dir }}/Library/Application Support/Firefox/Profiles/hardened.default/user.js"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    backup: true

