---
#### Grab your dotfiles
# Set dotfiles_repo in vars/main
# dotfiles_dir is set in defaults, LEAVE ALONE
####

- name: Install powerline
  become: true
  become_user: "{{ usernm }}"
  pip:
    name: powerline-status
    extra_args: --user
- name: Get powerline path
  become: true
  become_user: "{{ usernm }}"
  shell: find "{{ home_dir }}" -name powerline.zsh
  register: powerline_path
- name: Install .zshrc template
  become: true
  become_user: root
  template:
    src: zshrc-template.j2
    dest: "{{ home_dir }}/.zshrc"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    backup: true

