---
#### Grab your dotfiles
# Set dotfiles_repo in vars/main
# dotfiles_dir is set in defaults, LEAVE ALONE
####

- name: Create dotfiles dir
  file:
    path="{{ dotfiles_dir }}"
    owner="{{ usernm }}"
    group="{{ groupnm }}"
    mode=0755

- name: Clone dotfiles repo
  git:
    repo="{{ dotfiles_repo }}"
    dest="{{ dotfiles_dir }}"
    update=yes
    accept_hostkey=yes
