---
#### Grab your dotfiles
# Set dotfiles_repo in vars/main
# dotfiles_dir is set in defaults, LEAVE ALONE
####

- name: Install gnu stow and git for dotfiles
  homebrew:
    package: "{{ item }}"
    status: present
  with_items:
    - stow
    - git

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    update: yes
    accept_hostkey: yes
    clone: yes
    force: yes
    key_file: "{{ ssh_dir }}/dotfiles"
  become: no

- name: Stow common files
  command: stow common
  args:
    chdir: "{{ dotfiles_dir }}"
    creates: ~/.mackup.cfg

- name: Stow other files depending on host type
  command: stow "{{ dotfiles_env }}"
  args:
    chdir: "{{ dotfiles_dir }}"
    creates: ~/.bash_aliases
