---
- name: Create dotfiles dir
  file:
    path="{{ dotfiles_dir }}"
    owner="{{ usernm }}"
    group="{{ usernm }}"
    mode=0755

- name: Clone dotfiles repo
  git:
    repo="{{ dotfiles_repo }}"
    dest="{{ dotfiles_dir }}"
    update=yes
    accept_hostkey=yes
