---
#### Grab your dotfiles
# Set dotfiles_repo in vars/main
# dotfiles_dir is set in defaults, LEAVE ALONE
####

- name: Install gnu stow and git for dotfiles
  homebrew:
    package: "{{ item }}"
    status: present
  with_items:
    - stow
    - git

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    update: true
    accept_hostkey: true
    clone: true
    force: true
  become: false

- name: Stow common files
  command: stow common
  args:
    chdir: "{{ dotfiles_dir }}"
    creates: ~/.mackup.cfg

- name: Stow other files depending on host type
  command: stow "{{ dotfiles_env }}"
  args:
    chdir: "{{ dotfiles_dir }}"
    creates: ~/.bash_aliases
