---
#### Grab your dotfiles
# Set dotfiles_repo in vars/main
# dotfiles_dir is set in defaults, LEAVE ALONE
####

- name: Install gnu stow and git for dotfiles
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - stow
    - git

- name: Check for {{ dotfiles_dir }}
  stat:
    path: "{{ dotfiles_dir }}"
  register: dotfiles

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    update: true
    accept_hostkey: true
    clone: true
  when: not dotfiles.stat.exists

- name: Change the remote to ssh
  git_config:
    name: remote.origin.url
    value: "git@github.com:{{ github_user }}/dotfiles.git"
    scope: local
    repo: "{{ dotfiles_dir }}"

- name: Stow common files
  command: stow common
  args:
    chdir: "{{ dotfiles_dir }}"
    creates: ~/.vimrc

- name: Stow {{ dotfiles_env }} files
  command: stow "{{ dotfiles_env }}"
  args:
    chdir: "{{ dotfiles_dir }}"
    creates: ~/Brewfile
