---
# tasks file for roles/update
- block:

  - name: Check for mas
    stat:
      path: /usr/local/bin/mas
    register: mas
    changed_when: False

  - name: Check for software updates and figure out if reboot is needed
    command: softwareupdate -l
    register: available_updates
    changed_when: False

  - name: Check for homebrew
    stat:
      path: /usr/local/bin/brew
    register: homebrew
    changed_when: False

  - name: Check for vim-plug plugin updates
    command: vim +PlugDiff +qall
    register: plug_update
    changed_when: False

  - name: Check for pip
    stat:
      path: /usr/local/bin/pip
    register: pip
    changed_when: False

  - name: Check for pip3
    stat:
      path: /usr/local/bin/pip3
    register: pip3
    changed_when: False

  - name: Check for pip-review
    stat:
      path: /usr/local/bin/pip-review
    register: pip_review
    when: pip.stat.exists or pip3.stat.exists
    changed_when: False

  - name: Check for npm
    stat:
      path: /usr/local/bin/npm
    register: npm
    changed_when: False

  - name: Check for ruby gems
    stat:
      path: /usr/local/bin/gem
    register: rubygems
    changed_when: False

  ignore_errors: True

- name: Update homebrew packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew.stat.exists

- name: Update vim-plug
  command: vim +PlugUpgrade +qall
  register: plug_upgrade
  changed_when: "'vim-plug has been upgraded' in plug_upgrade.stdout"

- name: Update vim-plug plugins
  command: vim +PlugUpdate +qall
  when: "'pending updates' in plug_update.stdout"

- name: Update pip packages
  command: pip-review --auto
  when: pip_review.stat.exists

- name: Update npm packages
  command: npm update
  when: npm.stat.exists

- name: Update rubygem packages
  command: gem update
  when: rubygems.stat.exists

- name: Update mas packages
  command: mas upgrade
  when: mas.stat.exists

- name: Update OS when there's a reboot necessary AND we're ok with rebooting
  command: softwareupdate -i -a
  when: ( available_updates.stdout | join('') | search("reboot") ) and reboot

- name: Update OS when no reboot is necessary
  command: softwareupdate -i -a
  when: ( not available_updates.stdout | join('') | search("reboot") )
