---
# tasks file for roles/mas
- name: Make sure mas is installed
  homebrew:
    name: mas
    state: present

- name: Get mas account status
  shell: 'mas account'
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  changed_when: false

# Mas signin is currently broken on High Sierra
# See https://github.com/mas-cli/mas/issues/107
#
#- name: Sign in to MAS when email is provided.
#  shell: 'mas signin --dialog "{{ mas_email }}"'
#  register: mas_signin_result
#  when: mas_signin_dialog and mas_account_result.rc == 1 and mas_email != ''
- block:

    - name: Signin to the App Store
      command: open -a /Applications/App\ Store.app

    - name: Convert commerce plist to xml
      command: plutil -convert xml1 ~/Library/Preferences/com.apple.appstore.commerce.plist

    - name: Wait for Primary Account string to know I've signed in
      wait_for:
          path: ~/Library/Preferences/com.apple.appstore.commerce.plist
          search_regex: PrimaryAccount

  when: not mas_account_result.stdout is search( mas_email )

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ mas_installed_apps }}"
  when: "'{{ item.id|default(item) }}' not in mas_list.stdout"

- name: Upgrade all apps (if configured).
  command: mas upgrade
  when: mas_upgrade_all_apps
  changed_when: false
