---
- name: kill_finder
  command: killall Finder
  ignore_errors: true

- name: kill_dock
  command: killall Dock
  ignore_errors: true

- name: kill_systemUIserver
  command: killall SystemUIServer
  ignore_errors: true
