---
- name: kill finder
  become: true
  become_user: "{{ usernm }}"
  command: killall Finder
  ignore_errors: true

- name: kill dock
  become: true
  become_user: "{{ usernm }}"
  command: killall Dock
  ignore_errors: true
