---
#### Set up downloads dirs for hazel

- name: Set up downloads folders for hazel
  file:
    path: "{{ home_dir }}/Downloads/{{ item }}"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    state: directory
    mode: 0755
  with_items:
    - Android
    - Audacity
    - Compressed
    - IMG
    - Important
    - Music
    - PDF
    - Pics
    - Video
    - Work

- name: Install hazel from homebrew
  homebrew_cask: 
    name: hazel
    state: present
