---
#### Set up downloads dirs for hazel
- name: Install hazel from homebrew
  homebrew_cask:
    name: hazel
    state: present

- name: Set up downloads folders for hazel
  file:
    path: "{{ home_dir }}/Downloads/{{ item }}"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    state: directory
    mode: 0755
  with_items: "{{ hazel_dirs }}"
