---
#### Set up downloads dirs for hazel
#
####

- name: Set up downloads folders for hazel
  file:
    path="{{ home_dir }}/downloads/{{ item }}"
    owner="{{ usernm }}"
    group="{{ usernm }}"
    mode=0755
  with_items:
    - Android
    - Audacity
    - Compressed
    - IMG
    - Important
    - Music
    - PDF
    - Pics
    - Video
    - Work
