---
#### Install all public repos from any git user
# Dont forget to set github_user
####

- name: Download all my project repos
  shell: curl -s https://api.github.com/users/{{ github_user }}/repos\?per_page\=100 | grep clone_url | awk -F '"' '{print $4}' | xargs -n 1 -P 4 git clone'"'
  args:
    chdir: "{{ projects_dir }}"
