---
# tasks file for roles/homebrew
- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew

- name: Set fact for homebrew existing
  set_fact:
    homebrew_exists: true
  when: homebrew.stat.exists

- name: Install brew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  with_items: "{{ homebrew_installed_packages }}"

- name: Remove any blacklisted packages
  homebrew:
    name: "{{ item }}"
    state: absent
  with_items: "{{ homebrew_blacklisted_packages }}"

- name: Install cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_apps }}"

- name: Check for brewfile
  stat:
    path: "{{ homebrew_brewfile_dir }}/Brewfile"
  register: homebrew_brewfile

- name: Install from Brewfile
  command: "brew bundle"
  args:
    chdir: "{{ homebrew_brewfile_dir }}"
  when: homebrew_brewfile.stat.exists and homebrew_use_brewfile
  changed_when: false
