---
# tasks file for roles/homebrew
# Gatekeeper breaks us installing a couple of things.
# We turn it off, install them, code sign them,
# then turn gatekeeper back on
- name: Check gatekeeper status
  command: spctl --status
  register: spctl_status
  changed_when: false
  failed_when: false

- name: Turn off gatekeeper
  command: spctl --master-disable
  become: true
  become_user: root
  when: spctl_status.stdout == 'assessments enabled'
  changed_when: false

- name: Install brew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  with_items: "{{ homebrew_installed_packages }}"

- name: Remove any blacklisted packages
  homebrew:
    name: "{{ item }}"
    state: absent
  with_items: "{{ homebrew_blacklisted_packages }}"

- name: Install cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_apps }}"

- name: Check for brewfile
  stat:
    path: "{{ homebrew_brewfile_dir }}/Brewfile"
  register: homebrew_brewfile

- name: Install from Brewfile
  command: "brew bundle"
  args:
    chdir: "{{ homebrew_brewfile_dir }}"
  when: homebrew_brewfile.stat.exists and homebrew_use_brewfile
  changed_when: false

- name: Code sign the tricky apps
  command: spctl --add "/Applications/{{ item }}"
  become: true
  become_user: root
  changed_when: false
  with_items:
      - Virtualbox.app
      - Viscosity.app

- name: Turn on gatekeeper
  command: spctl --master-enable
  become: true
  become_user: root
  when: spctl_status.stdout == 'assessments disabled'
  changed_when: false
