---
#### Install packages using Homebrew

- name: Install homebrew (lil hacky to get unattended install)
  command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
  args:
    creates='/usr/local/bin/brew'
