---
# tasks file for roles/homebrew
- name: Refresh sudo cache so homebrew cask doesnt ask for a password
  command: "echo none"
  become: true
  changed_when: true

- name: Install brew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install Homebrew packages
  homebrew:
    name: "{{ homebrew_installed_packages }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present

- name: Remove any blacklisted packages
  homebrew:
    name: "{{ homebrew_blacklisted_packages }}"
    state: absent

- name: Install cask applications
  homebrew_cask:
    name: "{{ homebrew_cask_apps }}"
    state: present
    ignore_errors: true

- name: Check for brewfile
  stat:
    path: "{{ homebrew_brewfile_dir }}/Brewfile"
  register: homebrew_brewfile

- name: Install from Brewfile
  command: "brew bundle"
  args:
    chdir: "{{ homebrew_brewfile_dir }}"
  when: homebrew_brewfile.stat.exists and homebrew_use_brewfile
  changed_when: false
