---
- name: Create directories
  file:
    path={{ item }}
    state=directory
    owner={{ usernm }}
    group={{ usernm }}
    mode=0755
  with_items:
    - "{{ directories.projects }}"
    - "{{ directories.ansible_secrets }}"
    - "{{ directories.dotfiles }}"

- name: Create ssh key(s)
  command: sudo -u {{ usernm }} ssh-keygen -t rsa -N "" -f {{ item }}
  with_items:
    "{{ ssh_keys }}"
