---
#### Tweak a lot of OSX built ins
# Set path for new finder window in vars/main
# Set path for screenshots in vars/main
# Set timezone in vars/main
#
# Not an exact list anywhere, but to see more defaults write options: http://www.defaults-write.com/
# need to quote the values because this module is a bit buggy
####

- name: Set screen resolution
# TODO: This is MBP-specific
  become: true
  become_user: root
  command: screenresolution set 2048x1280x32@0

- name: Set display sleep to 5 mins on battery
  become: true
  become_user: root
  command: pmset -b displaysleep 5

- name: Global tweaks (or tweaks that don't require a notify)
  become: true
  become_user: "{{ usernm }}"
  osx_defaults:
    domain: "{{ item.domain | default('NSGlobalDomain') }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    "{{ global_defaults }}"

- name: Finder tweaks
  become: true
  become_user: "{{ usernm }}"
  osx_defaults:
    domain: "{{ item.domain | default('com.apple.finder') }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    "{{ finder_defaults }}"
  notify: kill finder

- name: Dock tweaks
  become: true
  become_user: "{{ usernm }}"
  osx_defaults:
    domain: "{{ item.domain | default('com.apple.dock') }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    "{{ dock_defaults }}"
  notify: kill dock

# 
# ### Misc tweaks

- name: Disable game center
  become: true
  become_user: root
  command: launchctl unload /System/Library/LaunchAgents/com.apple.gamed.plist

# Not working as of APFS
# - name: Disable local Time Machine snapshots
#  become: true
#  become_user: root
#  command: tmutil disablelocal

- name: Stop iTunes from responding to the keyboard media keys
  become: true
  become_user: root
  shell: launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

- name: Restart automatically if the computer freezes
  become: true
  become_user: root
  command: systemsetup -setrestartfreeze on

# - name: Never go into computer sleep mode
#   shell: "systemsetup {{ item.name }} {{ item.value }} > {{ item.redirect }}"
#   with_items:
#     - { name: -setcomputersleep, value: Off, redirect: /dev/null }
#     - { name: -settimezone, value: "{{ timezone }}", redirect: /dev/null }

- name: SSD Tweaks
  become: true
  become_user: root
  command: "pmset -a {{ item.name }} {{ item.value }}"
  with_items:
    # Disable sudden motion sensor if you have an SSD
    - { name: sms, value: 0 }
    # Disable hibernate mode; useful with SSD
    # - { name: hibernatemode, value: 0 }

# - name: Check size of sleep image
#   stat:
#     path: "{{ sleepimage }}"
#   register: sleep_image
# 
# - name: Remove the sleep image file to save disk space
#   become: true
#   become_user: root
#   command: "{{ item }}"
#   when: ("{{ sleep_image }}") and ("{{ sleep_image }}.stat.size != 0")
#   with_items:
#     - rm -f "{{ sleepimage }}"
#     - touch "{{ sleepimage }}"
#     - chflags uchg "{{ sleepimage }}"
# 
- name: Always show the Users' Library folder
  become: true
  become_user: "{{ usernm }}"
  command: chflags nohidden {{ home_dir }}/Library/

- name: Adium Event Notifications
  become: true
  become_user: "{{ usernm }}"
  copy:
    src: "files/{{ item }}.plist"
    dest: "{{ home_dir }}/Library/Application Support/Adium 2.0/Users/Default/{{ item }}.plist"
    owner: "{{ usernm }}"
    group: "{{ groupnm }}"
    mode: 0750
  with_items:
    - "Status Preferences"
    - "Event Presets"
    - "Contact Alerts"
    - "Address Book"
