---
# tasks file for roles/vim
- name: Install vim
  homebrew:
      name: vim
      state: present

# This makes sure that my vimrc is stowed from my dotfiles repo
- name: Check for vimrc being a link
  stat:
      path: "{{ home_dir }}/.vimrc"
  register: vimrc_link
  changed_when: false

- name: Check for plugged directory
  stat:
      path: "{{ vim_plug_dir }}"
  register: plug_dir
  changed_when: false

- name: Check if plugs are installed
  command: vim +PlugStatus +qall
  register: plug_status
  changed_when: false
  when: ( vimrc_link.stat.exists and vimrc_link.stat.islnk ) and plug_dir.stat.exists

- name: Install Vim plugs
  command: vim +PlugInstall +qall
  register: plug_installed
  changed_when: "'remote' in plug_installed.stdout"
  when: "'Not found' in plug_status.stdout"

- name: Check if there are any empty directories in {{ vim_plug_dir }}

- name: Clean Vim plug
  command: vim '+PlugClean!' +qall
  register: plug_clean
  changed_when: "not 'Already clean.' in plug_clean.stdout"
