---
#### Set up OSX machines
# One variable to set up is usernm in group_vars/all
# Comment out any module you don't want, buuuut
# beware dependencies of modules
####
- name: Set up osx host
  hosts: osx
  connection: local
  vars_prompt:
    - name: "full_name"
      prompt: "What is your full name?"
    - name: "groupnm"
      prompt: "What is your group name?"
    - name: "email"
      prompt: "What is your email?"
    - name: "hostname"
      prompt: "What do you want your hostname to be?"
    - name: "usernm"
      prompt: "What is your username?"
	- name: "mas_email"
      prompt: "What is your Mac App Store email?"
    - name: "mas_passwd"
      prompt: "What is your Mac App Store Password?"
  user: "{{ usernm }}"
  roles:
    - { role: 'osx_base', tags: 'osx_base' }
    - { role: 'homebrew', tags: 'homebrew' }
    - { role: 'packages', tags: 'packages' }
	- { role: 'mas', tags: 'mas' }
    - { role: 'git', tags: 'git' }
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'mackup', tags: 'mackup'}
    - { role: 'hazel', tags: 'hazel' }
    - { role: 'tweaks', tags: 'tweaks' }
