---
#### Set up OSX machines
# One variable to set up is usernm in group_vars/all
# Comment out any module you don't want, buuuut
# beware dependencies of modules
####
- name: Set up osx host
  hosts: osx
  connection: local
  vars_files:
    - [ local.yml, defaults.yml ]
  user: "{{ usernm }}"
  roles:
    - { role: 'osx_base', tags: 'osx_base' }
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'homebrew', tags: 'homebrew' }
    - { role: 'mas', tags: 'mas' }
    - { role: 'git', tags: 'git' }
    - { role: 'hazel', tags: 'hazel' }
    - { role: 'tweaks', tags: 'tweaks' }
