---
#### Set up OSX machines
# Comment out any module you don't want, but
# beware dependencies of modules
####
- name: Set up osx host
  hosts: osx
  connection: local
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
          - "{{ inventory_dir }}/local.yml"
          - "{{ inventory_dir }}/defaults.yml"
      tags:
          - osx_base
          - dotfiles
          - homebrew
          - mas
          - macos_install
          - github
          - hazel
          - tweaks
          - vim-plug
  roles:
    - { role: 'osx_base', tags: 'osx_base' }
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'homebrew', tags: 'homebrew' }
    - { role: 'mas', tags: 'mas' }
    - { role: 'macos_install', tags: 'macos_install' }
    - { role: 'github', tags: 'github' }
    - { role: 'hazel', tags: 'hazel' }
    - { role: 'tweaks', tags: 'tweaks' }
    - { role: 'vim-plug', tags: 'vim-plug' }
